### ISSUE TITLE
Failed to Resolve a DID document

### ISSUE THREAD

**Issue by m-yahya** [uport-project/ethr-did-resolver#32]
### Description
I'm trying to resolve a DID document using `did-resolver` and `ethr-did-resolver` using the instructions described here:
https://github.com/uport-project/ethr-did-resolver#resolving-a-did-document

### Sample Code
```
const Web3 = require('web3');
Web3.providers.HttpProvider.prototype.sendAsync = Web3.providers.HttpProvider.prototype.send
let provider = new Web3.providers.HttpProvider('http://localhost:9545')

const { Resolver } = require('did-resolver')
const { getResolver } = require('ethr-did-resolver')

const EthrDID = require('ethr-did');

let test = async () => {
    const registry = '0x71d2fb13e289fbb9ccae91571ca6637ccb29c727';
    const address = '0x23149630a1a84df75a8dccc3a50c02d0ad146d8e';

    const ethrDid = new EthrDID({ provider, registry, address });

    let did = ethrDid.did;

    const ethrDidResolver = getResolver(provider, registry)
    const didResolver = Resolver(ethrDidResolver)
    console.log(didResolver); // undefined

}

test();
```

### Steps to Reproduce

1. init npm project
2. paste the above code into `index.js`
3. config the provider
4. replace the `address` and `registry` with your own stuff
5. install the `web3`, `ethr-did`, `did-resolver`, `ethr-did-resolver` dependencies
6. run `node index.js`

### Expected Behaviour

It should resolve the DID Document for give DID.

### Actual Behaviour

`const didResolver = Resolver(ethrDidResolver)` is `undefined` so the rest of code (`didResolver.resolve('did:ethr:0x23149630a1a84df75a8dccc3a50c02d0ad146d8e').then(doc => console.log)`) is not executing.

### Versions

`"did-resolver": "^1.0.0",`
 `"ethjs-provider-http": "^0.1.6",`
`"ethr-did": "^1.1.0",`
`"ethr-did-resolver": "^1.0.1",`
`"web3": "^1.2.1"`

**Comment by mirceanis** [comment]
I think you are missing a `new` keyword
```js
const didResolver = Resolver(ethrDidResolver)
// should be
const didResolver = new Resolver(ethrDidResolver)
```

**Comment by m-yahya** [comment]
Thank you very much for your support.
It's working.
